1. Add 10 numbers using functions in Python Programming. Func1() will take 10
arguments in the form of 10 numbers and print the summation result. Accordingly,
Func2() will take 10 numbers by using the concept of reference variable or keyword
arguments and simultaneously add those. Compute the time constraints of these two
functions.

In [ ]:
def func1(num1, num2, num3, num4, num5, num6, num7, num8, num9, num10):
  return sum([num1,num2,num3,num4,num5,num6,num7,num8,num9,num10])

def func2(*kwargs):
  return sum(list(kwargs))

%timeit func1(1,2,3,4,5,6,7,8,9,0)
%timeit func2(1,2,3,4,5,6,7,8,9,0)


211 ns ± 10.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
334 ns ± 91.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


2. Create a 3x3 matrix and perform LU factorization.

In [ ]:
import numpy as np
import scipy as sp

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
p,l,u=sp.linalg.lu(matrix)
print("p - \n",p)
print("l - \n",l)
print("u - \n",u)

p - 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
l - 
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
u - 
 [[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]


3. Create one-dimensional, two-dimensional, and three-dimensional arrays using Numpy
module and accordingly compute the speed of different arrays.


In [ ]:
import numpy as np

size = 200

array_1d = np.random.rand(size)
array_2d = np.random.rand(size, size)
array_3d = np.random.rand(size, size, size)

%timeit np.sum(array_1d)

%timeit np.sum(array_2d)

%timeit np.sum(array_3d)


2.9 µs ± 91.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
13.8 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.35 ms ± 182 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


4. What is the sparsity of a matrix? Create a sparse matrix and find the sparsity of the
matrix.

In [6]:
# A sparse matrix is a matrix with most of its elements as zeros
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse import random

#SciPy sparse matrix with zeros
sparse_matrix = csr_matrix((1000, 1000))

n = 100
m = 100
# sparse SciPy matrix with random values and a specified sparsity level
sparsity = 0.7  # Adjust the sparsity level (0.0 to 1.0)
sparse_matrix = random(n, m, density=sparsity, format='csr')
print(sparse_matrix)

  (0, 0)	0.7206662802122202
  (0, 1)	0.5251996115331767
  (0, 2)	0.9801238497948884
  (0, 3)	0.18556004539233162
  (0, 4)	0.25736318461382945
  (0, 5)	0.09036446867942594
  (0, 6)	0.5982071223696397
  (0, 7)	0.2048837613357325
  (0, 8)	0.9485494326068735
  (0, 10)	0.25690341247278614
  (0, 12)	0.7641614299475349
  (0, 13)	0.8200194688226321
  (0, 14)	0.344164724025522
  (0, 15)	0.3001891859814859
  (0, 16)	0.9382536852333909
  (0, 17)	0.24419760117350264
  (0, 19)	0.8800792175134675
  (0, 20)	0.6412611668258483
  (0, 21)	0.8761710699850846
  (0, 22)	0.07239927500537402
  (0, 23)	0.6993926333909639
  (0, 24)	0.5458147138699131
  (0, 26)	0.21218578788321962
  (0, 27)	0.13859963953868382
  (0, 28)	0.19223112448236523
  :	:
  (99, 57)	0.08608123120447764
  (99, 62)	0.3401044295725629
  (99, 64)	0.9480541167999015
  (99, 65)	0.763622198672939
  (99, 67)	0.43535181533477674
  (99, 68)	0.45247198548016854
  (99, 69)	0.2663953873872841
  (99, 70)	0.6269126389088717
  (99, 71)	0.622168715396775

5. Create a dataframe like:  
Id Age Salary  
1 32 10000  
2 21 15000  
3 54 20000  
4 34 24000  
5 87 57000  
6 43 45000  
7 28 87000  
8 59 31000  
9 45 35000  
10 47 65000  
Now compute the mean, median, and S.D. of the data. Apply MinMaxScaling
technique to compute each and every rows of Salary column.
MinMaxScaling formula = (data(salary) – minimum of data(salary))/(maximum of
data(salary)-minimum of data (salary))

In [ ]:
import pandas as pd
dic={"Id":[1,2,3,4,5,6,7,8,9,10],"Age":[32,21,54,34,87,43,28,59,45,47],"Salary":[10000,15000,20000,24000,57000,45000,87000,31000,35000,65000]}
df=pd.DataFrame(dic)
df["Salary MinMax"]=(df['Salary']-min(df['Salary']))/(max(df['Salary'])-min(df['Salary']))
print(df)
df.describe()

   Id  Age  Salary  Salary MinMax
0   1   32   10000       0.000000
1   2   21   15000       0.064935
2   3   54   20000       0.129870
3   4   34   24000       0.181818
4   5   87   57000       0.610390
5   6   43   45000       0.454545
6   7   28   87000       1.000000
7   8   59   31000       0.272727
8   9   45   35000       0.324675
9  10   47   65000       0.714286


Id        Age        Salary  Salary MinMax
count  10.00000  10.000000     10.000000      10.000000
mean    5.50000  45.000000  38900.000000       0.375325
std     3.02765  18.867962  24546.780735       0.318789
min     1.00000  21.000000  10000.000000       0.000000
25%     3.25000  32.500000  21000.000000       0.142857
50%     5.50000  44.000000  33000.000000       0.298701
75%     7.75000  52.250000  54000.000000       0.571429
max    10.00000  87.000000  87000.000000       1.000000

6. F(x)=x^2 within an interval [0,1]. What would be the value for definite integral?

$ \int_{0}^{1} x^2 \,dx
= [\frac{x^3}{3}]_0^1
= [\frac{1}{3}-\frac{0}{3}]
= \frac{1}{3}$

In [4]:
import scipy.integrate as spi

def f(x):
    return x**2

result, error = spi.quad(f, 0, 1)
print("The definite integral is:", result)

The definite integral is: 0.33333333333333337


7. X = [2,4,5,9,14], and y = [3.5,4.1,5.2,9.1,17]   
Find the slope and intercept values
after computing linear regression using scipy module.


8. What is the difference between list and arrays?


In [ ]:
#List can contain multiple datatypes (Heterogeneous) and usually cannot handle mathematical operations
list1=[1,3.4,'hello']

#Arrays are homogeneous and can handle mathematical operations
array1=[1,2,3,4]
array2=np.array([1,2,3,4])


9. Two sets are present. Set A is consisting = {1,2,3,4,5}, and set B is consisting ={4,5,6,7,8}.  
 Now figure out the intersection points, and A-B from these two sets.



In [ ]:
a={1,2,3,4,5}
b={4,5,6,7,8}
print(f"Intersection of set A and set B - {a.intersection(b)}")
print(f"Set A - Set B = {a.difference(b)}")

Intersection of set A and set B - {4, 5}
Set A - Set B = {1, 2, 3}


10. Define a square matrix and find out the eigenvalues and eigenvectors.

In [ ]:
#A square matrix is a matrix that has an equal number of rows and columns
import numpy as np
from scipy.linalg import eig
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

eigenvalues, eigenvectors = eig(A)
print(f"Eigenvalues : \n{eigenvalues}")
print(f"Eigenvectors : \n{eigenvectors}")

Eigenvalues : 
[ 1.61168440e+01+0.j -1.11684397e+00+0.j -1.30367773e-15+0.j]
Eigenvectors : 
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


11. What do you mean by dimensionality reduction?  
 Create a 10x10 matrix and reduce the dimensions of the matrix where components would be 5 and print the value.


In [2]:
#Dimensionality reduction is the process of reducing the number of features (or dimensions) in a dataset
#while retaining as much information as possible

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

df = pd.DataFrame(np.random.rand(10, 10))

scalar = StandardScaler()
scaled_data = pd.DataFrame(scalar.fit_transform(df))
print(scaled_data)

pca = PCA(n_components = 5)
pca.fit(scaled_data)
data_pca = pca.transform(scaled_data)
data_pca = pd.DataFrame(data_pca,columns=['PC1','PC2','PC3','PC4','PC5'])
print(data_pca.head())

          0         1         2         3         4         5         6  \
0  0.613005  0.412427  0.011453  0.855103  0.933908  0.226210  0.487519   
1  0.213303  0.122206  0.908999  0.070411  0.653238  0.500705  0.820184   
2  0.830311  0.586630  0.007982  0.760327  0.996389  0.980284  0.657532   
3  0.272874  0.004134  0.587768  0.931314  0.282586  0.957735  0.024541   
4  0.470358  0.777488  0.959188  0.882861  0.497980  0.731795  0.319217   
5  0.078649  0.380375  0.789201  0.784545  0.298648  0.693828  0.583598   
6  0.653882  0.058690  0.848015  0.735642  0.614205  0.193216  0.423601   
7  0.350253  0.596340  0.098952  0.908856  0.482104  0.064623  0.745142   
8  0.313526  0.884875  0.222925  0.559977  0.585432  0.102296  0.347465   
9  0.404815  0.007854  0.702289  0.986324  0.868977  0.291320  0.466898   

          7         8         9  
0  0.456947  0.865360  0.136827  
1  0.722662  0.096761  0.736908  
2  0.094135  0.448097  0.749486  
3  0.272616  0.033481  0.644768  
4  0

12. Consider the dataset :  
X Y  
100 855  
150 780  
410 444  
105 673  
450 785  
720 109  
735 175  
801 193  
987 1020  
441 78  
Get the mean covariance from the above dataset without using any inbuilt functions.  
Find out the correlation matrix of the dataset

In [ ]:
df=pd.DataFrame({"x":[100,150,410,105,450,720,735,801,987,441],"y":[855,780,444,673,785,109,175,193,1020,78]})

print(f"Covariance Matrix : \n{df.cov()}")

df.x=df.x-df.x.mean()
df.y=df.y-df.y.mean()
df['cov']=df['x']*df['y']
covariance=sum(df['cov'])

print(f"\nCovariance : {covariance}")

Covariance Matrix : 
              x              y
x  98108.988889  -32564.200000
y -32564.200000  124299.955556

Covariance : -293077.80000000005
